name: Copy Files to Another Branch

on:
  push:
    branches:
      - main  # Replace with the source branch name

jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the repository
      
      - name: Copy Files
        run: |
          # Switch to the destination branch where you want to copy files
          git checkout alpha  # Replace with the destination branch name
          
        
        

